// interface OldCeshtja {
//     Id?: string,
//     "Emri?": string,
//     "Mbiemri?": string,
//     "Data_e_ngjarjes?": string,
//     "Kategoria?": string,
//     "Sipas Nenit?": string,
//     "Policia?": string,
//     "Prokuroria?": string,
//     "Sipas Nenit_P?": string,
//     "Masa e sigurisë kërkuar nga Prokurori?": string,
//     "Data Vendimit Pr?": string,
//     "Gjykata?": string,
//     "Hetimi?": string,
//     "Data Vedim Gjk?": string,
//     "Gjygjtari paraprak?": string,
//     "Neni_GJP?": string,
//     "Data Gjygjtari pr?": string,
//     "Masa e sigurise Gjykata Shk1?": string,
//     "Data mases Gjykates Shk1?": string,
//     "Vendimi Gjykates Shk1?": string,
//     "Neni_GJSH1"
//     "Data Vendimit GJ SH1?": string,
//     "Vendimi Apelit?": string,
//     "Neni_Apeli?": string,
//     "Data Vendim Apeli?": string,
//     "Masa e sigurisë në Gjykatën e Apelit?": string,
//     "Data mas sig Apeli?": string,
//     "Vendim Gjykata Larte?": string,
//     "Data Gjykata Larte?": string,
//     "Neni_GJL?": string,
//     "Masa e sigurisë në Gjykatën e Larte?": string,
//     "Data mas sig Gj Larte?": string,
//     "Komente?": string,
// }